apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-reducer-deployment
  labels:
    app: number-reducer-k8s
spec:
  selector:
    matchLabels:
      project: number-reducer
  template:
    metadata:
      labels:
        project: number-reducer
    spec:
      containers:
        - name: number-reducer-web
          image: vitaliysherstuk/number-reducer:0.0.1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: number-reducer-service
  labels:
    env: DEV
spec:
  selector:
    project: number-reducer
  ports:
    - name: number-reducer-listener
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer